
image: $DOTNET_SDK
    
   
stages:
  - build_api
  - build_mvc
  - deploy_api
  - deploy_mvc

variables:
  # Define your Azure-specific variables
  # AZURE_RESOURCE_GROUP: Inventario-App
  # AZURE_API_APP_NAME: ApiInventario
  # AZURE_MVC_APP_NAME: sistemadeinventario
  # AZURE_REGION: East US 

  
#   AZURE_API_PACKAGE_PATH: Inventario.SI\publish
#   AZURE_MVC_PACKAGE_PATH: Inventario.webApp\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  API_WORKING_DIRECTORY: Inventario.SI
  MVC_WORKING_DIRECTORY: Inventario.WebApp
  SERVICES_TIMEOUT: 60m  # Increase the timeout to 60 minutes
  # DOCKER_TLS_CERTDIR: ""
  # DOCKER_HOST: tcp://docker:2376/

before_script:
  # Install dependencies and prepare environment
   
    - dotnet restore $API_WORKING_DIRECTORY
    - dotnet restore $MVC_WORKING_DIRECTORY


build_api:
  stage: build_api
 
  script:
    - cd $API_WORKING_DIRECTORY
    - dotnet build --configuration Release

build_mvc:
  stage: build_mvc
  script:
    - cd $MVC_WORKING_DIRECTORY
    - dotnet build --configuration Release


deploy_api:
  
  stage: deploy_api
      
  script:
    - cd $API_WORKING_DIRECTORY
    - dotnet publish --configuration Release --output publish
    - apt-get update && apt-get -y install zip
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    - az login -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET 
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_API_APP_NAME --src publish/Inventario.SI.zip

deploy_mvc:
  
  stage: deploy_mvc
  
    
  script:
    - cd $MVC_WORKING_DIRECTORY
    - dotnet publish --configuration Release --output publish
    - dotnet restore --configfile ./NuGet.config 
   
    - apt-get update && apt-get -y install zip
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    - az login -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET 
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_MVC_APP_NAME --src publish/Inventario.WebApp.zip

