image: $DOTNET_SDK


stages:
  - build_api
  - build_mvc
  - deploy_api
  - deploy_mvc

variables:
  # Define your Azure-specific variables
  # AZURE_RESOURCE_GROUP: Inventario-App
  # AZURE_API_APP_NAME: ApiInventario
  # AZURE_MVC_APP_NAME: sistemadeinventario
  # AZURE_REGION: East US 

  
#   AZURE_API_PACKAGE_PATH: Inventario.SI\publish
#   AZURE_MVC_PACKAGE_PATH: Inventario.webApp\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  API_WORKING_DIRECTORY: Inventario.SI
  MVC_WORKING_DIRECTORY: Inventario.WebApp

before_script:
  # Install dependencies and prepare environment
   
    - dotnet restore $API_WORKING_DIRECTORY
    - dotnet restore $MVC_WORKING_DIRECTORY


build_api:
  stage: build_api
  script:
    - cd $API_WORKING_DIRECTORY
    - dotnet build --configuration Release

build_mvc:
  stage: build_mvc
  script:
    - cd $MVC_WORKING_DIRECTORY
    - dotnet build --configuration Release


deploy_api:
  
  stage: deploy_api
  services:
    - name: mcr.microsoft.com/azure-cli
      alias: azcli
  script:
    - cd $API_WORKING_DIRECTORY
    - dotnet publish --configuration Release --output publish
    - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_API_APP_NAME --src publish/ApiProject.zip

deploy_mvc:
  
  stage: deploy_mvc
  services:
    - name: mcr.microsoft.com/azure-cli
      alias: azcli
  script:
    - cd $MVC_WORKING_DIRECTORY
    - dotnet publish --configuration Release --output publish
    - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_MVC_APP_NAME --src publish/MvcProject.zip

